# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-19 17:59
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.IntegerField(choices=[(1, 'Air'), (0, 'Ground')], default=0)),
                ('image', models.FileField(upload_to='documents/%Y/%m/%d')),
                ('localization_name', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('initial_date', models.DateField(verbose_name='Initial date')),
                ('initial_time', models.TimeField(verbose_name='Initial time')),
            ],
        ),
        migrations.CreateModel(
            name='RaceParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Participant')),
                ('race', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race')),
            ],
        ),
        migrations.AddField(
            model_name='position',
            name='raceposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.RaceParticipant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='races',
            field=models.ManyToManyField(through='races.RaceParticipant', to='races.Race'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
