# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='position',
            old_name='raceposition',
            new_name='raceparticipant',
        ),
    ]
