# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-10 14:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('races', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.DateTimeField(auto_now=True)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RaceParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Participant')),
            ],
        ),
        migrations.AddField(
            model_name='race',
            name='type',
            field=models.IntegerField(choices=[(1, 'Air'), (0, 'Ground')], default=0),
        ),
        migrations.AlterField(
            model_name='race',
            name='initial_date',
            field=models.DateField(verbose_name='Initial date'),
        ),
        migrations.AlterField(
            model_name='race',
            name='initial_time',
            field=models.TimeField(verbose_name='Initial time'),
        ),
        migrations.AddField(
            model_name='raceparticipant',
            name='race',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Race'),
        ),
        migrations.AddField(
            model_name='position',
            name='raceposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.RaceParticipant'),
        ),
        migrations.AddField(
            model_name='participant',
            name='races',
            field=models.ManyToManyField(through='races.RaceParticipant', to='races.Race'),
        ),
        migrations.AddField(
            model_name='participant',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
