# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0002_auto_20160620_1439'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='position',
            name='raceparticipant',
        ),
        migrations.AddField(
            model_name='raceparticipant',
            name='positions',
            field=models.ManyToManyField(to='races.Position'),
        ),
    ]
