# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-20 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0004_auto_20160620_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='instant',
            field=models.IntegerField(default=0),
        ),
    ]
