# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 11:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0006_auto_20160621_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='raceparticipant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.RaceParticipant'),
        ),
    ]
