# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-28 21:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0007_auto_20160621_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirRace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('folderPath', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AirRaceParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmlpath', models.FileField(upload_to='airraces/')),
                ('airrace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.AirRace')),
            ],
        ),
    ]
