# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0008_airrace_airraceparticipant'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirCompetition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.CharField(max_length=100)),
            ],
        ),
    ]
