# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0009_aircompetition'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTaskParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kmlpath', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('imageURL', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d')),
            ],
        ),
        migrations.RenameModel(
            old_name='AirCompetition',
            new_name='Competition',
        ),
        migrations.AddField(
            model_name='task',
            name='competition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Competition'),
        ),
        migrations.AddField(
            model_name='competitiontaskparticipant',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.Task'),
        ),
    ]
