# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 09:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0010_auto_20160707_1338'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompetitionTaskParticipantPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instant', models.IntegerField(default=0)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('height', models.CharField(max_length=100)),
                ('raceparticipant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='races.CompetitionTaskParticipant')),
            ],
        ),
        migrations.AlterField(
            model_name='task',
            name='file',
            field=models.FileField(upload_to='static/competitions'),
        ),
    ]
