# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-03 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0013_auto_20160714_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitiontaskparticipant',
            name='visibility',
            field=models.BooleanField(default=False),
        ),
    ]
