# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-11 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('races', '0014_competitiontaskparticipant_visibility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='image',
            field=models.CharField(max_length=100),
        ),
    ]
